layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: carolin-beer
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  website: carolin.beer
  # youtube: your_username

topics:
  # - name: Distributed systems
  #   web_url:
  #   image_url:
  - name: Distributed systems
    image_url: https://atos.net/wp-content/uploads/2018/01/Trusted-Blockchain-300x300.png

  - name: Security
    image_url: https://www.structured.com/wp-content/uploads/2017/09/Network-Security-Icon.png

  - name: Energy markets 
    image_url: https://procom-energy.de/en/wp-content/uploads/sites/4/2016/12/ProCom_Icon-Bilanzkreisverantwortlicher.png

